package org.brokenarrow.lootboxes.menus;

public enum MenuKeys {
	EDIT_KEYS_FOR_OPEN_MENU,
	MATRIALLIST_MENU,
	ALTER_CONTAINER_DATA_MENU,
	CUSTOMIZEITEM_MENU,
	KEY_SETTINGS_MOBDROP,
	ENTITY_TYPE_LISTMENU,
	EDITKEY,
	PARTICLE_ANIMANTION,


}
