name: Lootboxes
version: ${project.version}
main: ${main.class}
author: broken
api-version: 1.13
softdepend: [PlaceholderAPI]

permissions:
  
  lootboxes.admin.*:
    description: to open the menus to edit tables and containers.
    default: false
    children:
      lootboxes.command.menu: true
      lootboxes.command.reload: true
      lootboxes.link.containers: true