# Main settings

Language: en
Blocks_Between_Containers: 10
Blocks_Away_From_Player: 30
Random_Continer_Spawn: false
Amount_Of_Blocks_Below_Surface: 5
Spawn_On_Surface: false
Warn_Before_Save_With_Metadata: true
Save_Metadata_On_Item: true
Remove_Container_When_player_close: true
Max_and_min_amount:
  Increse_with: 10
  Decrese_with: 10
Link_tool:
  Item: GOLDEN_SHOVEL
  Display_name: "&3Link tool"
  Lore:
    - "&aThis tool can you add or remove"
    - "&aLink to container, change slot"
    - "&aor drop item to cancel."
Place_container:
  Display_name: "&3Place this&6 {0}"
  Lore:
    - "&3When you place the container it will"
    - "&3be saved and if you remove the container"
    - "&3it will be removed."