######################################################
# Settings for a particle in this menu.
Menus:
  menu:
    menu_settings:
      name: "&1Edit this particle {0}"
      sound: null
      size: 45
    buttons:
      "10":
        action_type: Particle_material
        passive:
          material: GOLDEN_APPLE
          name: "&6Can't set material"
          glow: false
          lore:
          - "&6"
          - "&aCurrent material is:&6 {1} "
        active:
          material: GOLDEN_APPLE
          name: "&6Change material {0}"
          glow: true
          lore:
          - "&6"
          - "&4This particle not use this"
          - "&4setting."
          - "&6"
          - "&aCurrent material is:&6 {1}"
      "12":
        action_type: Data
        passive:
          material: PAPER
          name: "&6Change data {0}"
          glow: false
          lore:
          - "&6"
          - "&aCurrent data is:&6 {1} "
        active:
          material: PAPER
          name: "&6Change data {0}"
          glow: true
          lore:
          - "&6"
          - "&aCurrent data is:&6 {1} "
      "14":
        action_type: Particle_colors
        passive:
          material: RED_WOOL
          name: "&6Can't set colors"
          glow: false
          lore:
          - "&6"
          - "&4This particle not use this"
          - "&4setting."
          - "&6"
          - "&aCurrent colors set:&6 {1} "
        active:
          material: RED_WOOL
          name: "&6Change color {0}"
          glow: true
          lore:
          - "&6"
          - "&aCurrent colors set:&6 {1} "
      "16":
        action_type: Particle_size
        passive:
          material: CYAN_DYE
          name: "&6Can't set size"
          glow: false
          lore:
          - "&6"
          - "&4This particle not use this"
          - "&4setting."
          - "&6"
          - "&aSize of the particle (for"
          - "&aredstone particle)."
          - "&6"
          - "&aCurrent size:&6 {1} "
        active:
          material: CYAN_DYE
          name: "&6Change size {0}"
          glow: true
          lore:
          - "&6"
          - "&aSize of the particle (for"
          - "&aredstone particle)."
          - "&6"
          - "&aCurrent size:&6 {1} "
      "44":
        action_type: Back_button
        material: CHORUS_FRUIT
        name: "&bBack"
        glow: true
        lore:
          - ""
          - "&2Go one page"
          - "&2back."
      "36-43":
        material: BLACK_STAINED_GLASS_PANE
        name: "&b"
        glow: false
        lore:
          - ""
      "0-8":
        material: BLACK_STAINED_GLASS_PANE
        name: "&b"
        glow: false
        lore:
          - ""